name: Deploy to EC2

on:
  push:
    branches:
      - main  # 원하는 브랜치로 설정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
           scp -o StrictHostKeyChecking=no -o ConnectTimeout=30 -r ./* ubuntu@52.78.154.108:/home/ubuntu/my-app/

      - name: Install dependencies
        run: |
           ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=30 ubuntu@52.78.154.108 'cd /home/ubuntu/my-app && npm install'

      - name: Start application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@52.78.154.108 'cd /home/ubuntu/my-app && npm start'
